version: '3.0'

services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './data:/usr/src/app/data:delegated'
      - './:/usr/src/app:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
